"""Tool implementations for the Linux diagnostics server."""

from .processes import (
    BasicProcessInfo,
    KillProcessResult,
    ProcessCpuUsage,
    ProcessDetailResult,
    ProcessMemorySnapshot,
    ProcessQueryResult,
    get_process_by_id,
    get_process_candidate_by_id,
    get_processes_by_name,
    kill_process,
    list_processes,
    sample_top_cpu_processes,
)
from .linux_diagnostics import (
    LinuxDiagnosticObservation,
    LinuxDiagnosticQuery,
    extract_sampling_text,
    read_linux_diagnostic,
    troubleshoot_linux_diagnostics,
    validate_linux_diagnostic_query,
)
from .log_snapshots import (
    LogSnapshotLine,
    LogSnapshotPage,
    LogSnapshotPagination,
    LogSnapshotSummary,
    clear_log_snapshots,
    create_log_snapshot,
    get_log_snapshot_page,
    render_log_snapshot_resource,
)
from .proc_snapshots import (
    ProcAccessResult,
    ProcRootsService,
    ProcSnapshotEntry,
    ProcSnapshotPage,
    ProcSnapshotPagination,
    ProcSnapshotSummary,
    clear_proc_snapshots,
    create_proc_snapshot,
    get_proc_snapshot_page,
    render_proc_snapshot_resource,
    request_proc_access,
    reset_proc_roots,
    validate_proc_snapshot_path,
)
from .system_info import SystemInfoResult, collect_system_info

ProcessInfoResult = ProcessDetailResult
ProcessMemoryUsage = ProcessMemorySnapshot
get_process_by_name = get_processes_by_name
get_process_list = list_processes

__all__ = [
    "BasicProcessInfo",
    "LogSnapshotLine",
    "LogSnapshotPage",
    "LogSnapshotPagination",
    "LogSnapshotSummary",
    "KillProcessResult",
    "LinuxDiagnosticObservation",
    "LinuxDiagnosticQuery",
    "ProcAccessResult",
    "ProcRootsService",
    "ProcSnapshotEntry",
    "ProcSnapshotPage",
    "ProcSnapshotPagination",
    "ProcSnapshotSummary",
    "ProcessCpuUsage",
    "ProcessDetailResult",
    "ProcessInfoResult",
    "ProcessMemorySnapshot",
    "ProcessMemoryUsage",
    "ProcessQueryResult",
    "SystemInfoResult",
    "collect_system_info",
    "create_log_snapshot",
    "create_proc_snapshot",
    "clear_log_snapshots",
    "clear_proc_snapshots",
    "extract_sampling_text",
    "get_process_by_id",
    "get_process_candidate_by_id",
    "get_processes_by_name",
    "get_process_by_name",
    "get_log_snapshot_page",
    "get_proc_snapshot_page",
    "kill_process",
    "list_processes",
    "get_process_list",
    "read_linux_diagnostic",
    "render_log_snapshot_resource",
    "render_proc_snapshot_resource",
    "request_proc_access",
    "reset_proc_roots",
    "sample_top_cpu_processes",
    "troubleshoot_linux_diagnostics",
    "validate_linux_diagnostic_query",
    "validate_proc_snapshot_path",
]
